# -*- coding: utf-8 -*-
"""HPC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXWmXafIbur3vGC1q_Snv_pdKzU8t0DX

**##Scalable HPC-Based Spatio-Temporal Energy Demand Forecasting with CPU–GPU Hybrid Parallelism**

**Install Required Libraries**
"""

# Install required packages
!pip install gradio xgboost plotly scikit-learn numba

"""**Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import time

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBRegressor

from numba import njit, prange

import gradio as gr

"""**Upload Dataset**"""

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

df.head()

"""**Data Preprocessing**"""

df['DateTime'] = pd.to_datetime(df['DateTime'])

df = df.sort_values("DateTime")
# Remove missing values
df = df.dropna()
df.reset_index(drop=True, inplace=True)

df.head()

"""**Feature Engineering**"""

df["hour"] = df["DateTime"].dt.hour
df["day_of_week"] = df["DateTime"].dt.dayofweek

# Lag features
df["lag1"] = df["Consumption"].shift(1)
df["lag2"] = df["Consumption"].shift(2)

# Rolling mean
df["rolling_mean"] = df["Consumption"].rolling(5).mean()

df = df.dropna()

df.head()

"""**HPC Sliding Window**"""

@njit(parallel=True)
def create_windows(data, window_size):

    X = []
    y = []

    for i in prange(len(data) - window_size):
        X.append(data[i:i+window_size])
        y.append(data[i+window_size])

    return np.array(X), np.array(y)

"""**Prepare Training Data**"""

features = ["Consumption","lag1","lag2","rolling_mean","hour","day_of_week"]

X = df[features]
y = df["Consumption"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

"""**Model 1 – Linear Regression**"""

start = time.time()

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_time = time.time() - start

lr_pred = lr_model.predict(X_test)

"""**Model 2 – XGBoost (Parallel CPU)**"""

start = time.time()

xgb_model = XGBRegressor(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

xgb_time = time.time() - start

xgb_pred = xgb_model.predict(X_test)

"""**Model Evaluation**"""

def evaluate(y_true, y_pred):

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    return mae, rmse, r2


lr_metrics = evaluate(y_test, lr_pred)
xgb_metrics = evaluate(y_test, xgb_pred)

print("Linear Regression:", lr_metrics)
print("XGBoost:", xgb_metrics)

"""**HPC Performance Comparison**"""

print("Execution Time")

print("Linear Regression:", lr_time)
print("XGBoost Parallel:", xgb_time)

speedup = lr_time / xgb_time

print("Speedup:", speedup)

"""**Peak Demand ML Classification**"""

threshold = df["Consumption"].quantile(0.9)

df["peak"] = (df["Consumption"] > threshold).astype(int)

X_class = df[features]
y_class = df["peak"]

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_class, y_class, test_size=0.2, shuffle=False
)

classifier = RandomForestClassifier()

classifier.fit(X_train_c, y_train_c)

peak_prob = classifier.predict_proba(X_test_c)[:,1]

"""**Visualization Charts**

Energy trend
"""

fig = px.line(df, x="DateTime", y="Consumption", title="Energy Consumption Trend")

fig.show()

"""Prediction vs Actual"""

result_df = pd.DataFrame({
    "Actual": y_test,
    "Predicted": xgb_pred
})

result_df.plot(figsize=(10,5))

plt.title("Actual vs Predicted Energy")

plt.show()

"""**Output CSV Generation**"""

output = X_test.copy()

output["actual_energy"] = y_test.values
output["predicted_energy"] = xgb_pred
peak_prob = classifier.predict_proba(X_test_c)[:,1] # Moved calculation here
output["peak_probability"] = peak_prob

output.to_csv("energy_predictions.csv", index=False)

output.head()

files.download("energy_predictions.csv")

"""**Gradio Interface**

**Real-Time Simulation**
"""

import time

for i in range(10):

    sample = X_test.iloc[i:i+1]

    pred = xgb_model.predict(sample)

    print("Predicted Demand:", pred[0])

    time.sleep(1)

"""**Final Dashboard Chart**"""

fig = px.scatter(
    output,
    x="predicted_energy",
    y="peak_probability",
    title="Peak Demand Risk"
)

fig.show()

import plotly.express as px
import plotly.graph_objects as go
import gradio as gr

import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import gradio as gr
from sklearn.ensemble import IsolationForest
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""**Train Anomaly Detection Model**"""

# Anomaly Detection Model

anomaly_model = IsolationForest(
    contamination=0.02,
    random_state=42
)

anomaly_model.fit(X_train)

"""**Real-Time Energy Simulation Function**"""

def simulate_realtime():

    values = np.random.normal(500, 50, 50)

    df = pd.DataFrame({
        "time": range(50),
        "energy": values
    })

    fig = px.line(
        df,
        x="time",
        y="energy",
        title="Real-Time Energy Consumption Simulation"
    )

    return fig

"""**Main Prediction Dashboard Function**"""

def predict_file(file):

    try:

        df = pd.read_csv(file)

        df.columns = df.columns.str.strip()

        if "Consumption" not in df.columns:
            if "energy" in df.columns:
                df.rename(columns={"energy":"Consumption"}, inplace=True)

        if "datetime" not in df.columns:
            df["datetime"] = pd.date_range(
                start="2024-01-01",
                periods=len(df),
                freq="H"
            )

        df["datetime"] = pd.to_datetime(df["datetime"])

        # Feature Engineering
        df["hour"] = df["datetime"].dt.hour
        df["day_of_week"] = df["datetime"].dt.dayofweek

        df["lag1"] = df["Consumption"].shift(1)
        df["lag2"] = df["Consumption"].shift(2)

        df["rolling_mean"] = df["Consumption"].rolling(5).mean()

        df = df.dropna()

        features = ["Consumption","lag1","lag2","rolling_mean","hour","day_of_week"]

        X = df[features]

        preds = xgb_model.predict(X)

        peak_prob = classifier.predict_proba(X)[:,1]

        df["predicted_energy"] = preds
        df["peak_probability"] = peak_prob

        anomaly_scores = anomaly_model.predict(X)

        df["anomaly"] = anomaly_scores
        df["anomaly"] = df["anomaly"].map({1:"Normal",-1:"Anomaly"})

        # KPI Metrics
        current_demand = round(df["Consumption"].iloc[-1],2)
        predicted_demand = round(df["predicted_energy"].iloc[-1],2)

        peak_risk = round(df["peak_probability"].iloc[-1]*100,2)

        anomaly_count = (df["anomaly"]=="Anomaly").sum()

        # Charts
        fig1 = px.line(df, x="datetime", y="Consumption",
                       title="Energy Consumption Trend")

        fig2 = go.Figure()

        fig2.add_trace(go.Scatter(
            x=df["datetime"], y=df["Consumption"], name="Actual"))

        fig2.add_trace(go.Scatter(
            x=df["datetime"], y=df["predicted_energy"], name="Predicted"))

        fig2.update_layout(title="Actual vs Predicted Energy")

        heatmap = px.density_heatmap(
            df, x="hour", y="day_of_week", z="Consumption",
            title="Peak Demand Heatmap")

        anomaly_chart = px.scatter(
            df, x="datetime", y="Consumption",
            color="anomaly", title="Energy Anomaly Detection")

        df.to_csv("prediction_output.csv", index=False)

        return (
            current_demand,
            predicted_demand,
            peak_risk,
            anomaly_count,
            df.head(20),
            fig1,
            fig2,
            heatmap,
            anomaly_chart,
            "prediction_output.csv"
        )

    except Exception as e:

        return None,None,None,None,pd.DataFrame({"Error":[str(e)]}),None,None,None,None,None

with gr.Blocks(title="AI Energy Intelligence Platform") as dashboard:

    gr.Markdown("# ⚡ AI Energy Intelligence Platform")

    gr.Markdown("Upload energy dataset to predict demand, detect peak loads, and monitor anomalies.")

    file_input = gr.File(label="Upload Energy CSV")

    # Add the demo dataset button here, inside the gr.Blocks context
    demo_button = gr.Button("Generate Demo Dataset")

    with gr.Row():

        current_card = gr.Number(label="⚡ Current Demand")

        predicted_card = gr.Number(label="📈 Predicted Demand")

        peak_card = gr.Number(label="⚠️ Peak Risk (%)")

        anomaly_card = gr.Number(label="🚨 Anomaly Alerts")

    result_table = gr.Dataframe(label="Prediction Results")

    # Connect the demo_button to the run_demo function (updated from generate_demo_dataset)
    demo_button.click(
        fn=run_demo,
        inputs=None,
        outputs=result_table
    )

    with gr.Row():

        chart1 = gr.Plot(label="Energy Consumption Trend")

        chart2 = gr.Plot(label="Prediction vs Actual")

    with gr.Row():

        chart3 = gr.Plot(label="Peak Demand Heatmap")

        chart4 = gr.Plot(label="Anomaly Detection")

    download_file = gr.File(label="Download Prediction CSV")

    run_button = gr.Button("Run AI Forecast")

    run_button.click(
        predict_file,
        inputs=file_input,
        outputs=[
            current_card,
            predicted_card,
            peak_card,
            anomaly_card,
            result_table,
            chart1,
            chart2,
            chart3,
            chart4,
            download_file
        ]
    )

dashboard.launch(share=True)

future_steps = 24

future_preds=[]

last_data=X_test.iloc[-1:]

for i in range(future_steps):

    pred=xgb_model.predict(last_data)[0]

    future_preds.append(pred)

    last_data["Consumption"]=pred

"""**Smart Grid Control Logic**"""

import numpy as np
import pandas as pd
import plotly.graph_objects as go

def smart_grid_simulation():

    demand = []
    supply = []
    status = []

    base = 500

    for i in range(50):

        # simulate demand fluctuation
        d = base + np.random.normal(0,40)

        demand.append(d)

        # AI control logic
        if d > 560:
            supply.append(580)
            status.append("Peak Control Activated")

        elif d < 450:
            supply.append(460)
            status.append("Low Demand")

        else:
            supply.append(520)
            status.append("Normal")

    df = pd.DataFrame({
        "time": range(50),
        "demand": demand,
        "supply": supply,
        "status": status
    })

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df["time"],
        y=df["demand"],
        name="Energy Demand"
    ))

    fig.add_trace(go.Scatter(
        x=df["time"],
        y=df["supply"],
        name="Grid Supply"
    ))

    fig.update_layout(
        title="Smart Grid AI Control Simulation",
        xaxis_title="Time",
        yaxis_title="Energy Level"
    )

    return df, fig

smart_grid = gr.Interface(
    fn=smart_grid_simulation,
    inputs=None,
    outputs=[
        gr.Dataframe(label="Smart Grid Status"),
        gr.Plot(label="Demand vs Supply Control")
    ],
    title="⚡ Smart Grid AI Control Simulation",
    description="AI automatically adjusts energy supply based on predicted demand."
)

app = gr.TabbedInterface(
    [dashboard, smart_grid],
    ["Energy Forecasting Platform", "Smart Grid Control"]
)

app.launch(share=True)



"""**Synthetic Energy Dataset Generator**"""

import numpy as np
import pandas as pd

def generate_demo_dataset():

    np.random.seed(42)

    hours = 500

    base_load = 500

    data = []

    for i in range(hours):

        # daily pattern
        hour_of_day = i % 24

        if 18 <= hour_of_day <= 22:
            demand = base_load + 120 + np.random.normal(0,20)
        elif 0 <= hour_of_day <= 5:
            demand = base_load - 80 + np.random.normal(0,15)
        else:
            demand = base_load + np.random.normal(0,25)

        data.append(demand)

    df = pd.DataFrame({
        "Consumption": data
    })

    return df

def run_demo():

    df = generate_demo_dataset()

    df["datetime"] = pd.date_range(
        start="2024-01-01",
        periods=len(df),
        freq="H"
    )

    df["hour"] = df["datetime"].dt.hour
    df["day_of_week"] = df["datetime"].dt.dayofweek

    df["lag1"] = df["Consumption"].shift(1)
    df["lag2"] = df["Consumption"].shift(2)

    df["rolling_mean"] = df["Consumption"].rolling(5).mean()

    df = df.dropna()

    features=["Consumption","lag1","lag2","rolling_mean","hour","day_of_week"]

    X=df[features]

    preds=xgb_model.predict(X)

    df["predicted_energy"]=preds

    return df.head(20)

import gradio as gr
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go


#############################################
# DEMO DATASET GENERATOR
#############################################

def generate_demo_dataset():

    np.random.seed(42)

    hours = 200
    base_load = 500
    data = []

    for i in range(hours):

        hour_of_day = i % 24

        if 18 <= hour_of_day <= 22:
            demand = base_load + 120 + np.random.normal(0,20)

        elif 0 <= hour_of_day <= 5:
            demand = base_load - 80 + np.random.normal(0,15)

        else:
            demand = base_load + np.random.normal(0,25)

        data.append(demand)

    df = pd.DataFrame({"Consumption":data})

    return df


#############################################
# MAIN AI PREDICTION FUNCTION
#############################################

def run_ai_pipeline(df):

    df["datetime"] = pd.date_range(
        start="2024-01-01",
        periods=len(df),
        freq="H"
    )

    df["hour"] = df["datetime"].dt.hour
    df["day_of_week"] = df["datetime"].dt.dayofweek

    df["lag1"] = df["Consumption"].shift(1)
    df["lag2"] = df["Consumption"].shift(2)

    df["rolling_mean"] = df["Consumption"].rolling(5).mean()

    df = df.dropna()

    features = [
        "Consumption",
        "lag1",
        "lag2",
        "rolling_mean",
        "hour",
        "day_of_week"
    ]

    X = df[features]

    preds = xgb_model.predict(X)

    peak_prob = classifier.predict_proba(X)[:,1]

    anomaly_scores = anomaly_model.predict(X)

    df["predicted_energy"] = preds
    df["peak_probability"] = peak_prob
    df["anomaly"] = anomaly_scores
    df["anomaly"] = df["anomaly"].map({1:"Normal",-1:"Anomaly"})


    #########################################
    # KPI VALUES
    #########################################

    current_demand = round(df["Consumption"].iloc[-1],2)

    predicted_demand = round(df["predicted_energy"].iloc[-1],2)

    peak_risk = round(df["peak_probability"].iloc[-1]*100,2)

    anomaly_count = (df["anomaly"]=="Anomaly").sum()


    #########################################
    # CHARTS
    #########################################

    energy_chart = px.line(
        df,
        x="datetime",
        y="Consumption",
        title="Energy Consumption Trend"
    )


    pred_chart = go.Figure()

    pred_chart.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["Consumption"],
        name="Actual"
    ))

    pred_chart.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["predicted_energy"],
        name="Predicted"
    ))

    pred_chart.update_layout(
        title="Actual vs Predicted Energy"
    )


    heatmap = px.density_heatmap(
        df,
        x="hour",
        y="day_of_week",
        z="Consumption",
        title="Peak Demand Heatmap"
    )


    anomaly_chart = px.scatter(
        df,
        x="datetime",
        y="Consumption",
        color="anomaly",
        title="Energy Anomaly Detection"
    )


    df.to_csv("prediction_output.csv",index=False)


    return (
        current_demand,
        predicted_demand,
        peak_risk,
        anomaly_count,
        df.head(20),
        energy_chart,
        pred_chart,
        heatmap,
        anomaly_chart,
        "prediction_output.csv"
    )


#############################################
# FILE UPLOAD HANDLER
#############################################

def predict_file(file):

    df = pd.read_csv(file)

    if "Consumption" not in df.columns:

        if "energy" in df.columns:
            df.rename(columns={"energy":"Consumption"},inplace=True)

    return run_ai_pipeline(df)


#############################################
# DEMO DATASET HANDLER
#############################################

def run_demo():

    df = generate_demo_dataset()

    return run_ai_pipeline(df)


#############################################
# SMART GRID SIMULATION
#############################################

def smart_grid_simulation():

    demand=[]
    supply=[]

    base=500

    for i in range(50):

        d = base + np.random.normal(0,40)

        demand.append(d)

        if d > 560:
            supply.append(580)

        elif d < 450:
            supply.append(460)

        else:
            supply.append(520)

    df = pd.DataFrame({
        "time":range(50),
        "demand":demand,
        "supply":supply
    })

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df["time"],
        y=df["demand"],
        name="Demand"
    ))

    fig.add_trace(go.Scatter(
        x=df["time"],
        y=df["supply"],
        name="Grid Supply"
    ))

    fig.update_layout(
        title="Smart Grid Control Simulation"
    )

    return df,fig


#############################################
# DASHBOARD UI
#############################################

with gr.Blocks(
    theme=gr.themes.Soft(),
    title="AI Energy Intelligence Platform"
) as dashboard:


    gr.Markdown("# ⚡ AI Energy Intelligence Platform")

    gr.Markdown(
    "AI system for forecasting electricity demand, detecting peak loads, and monitoring anomalies."
    )


    file_input = gr.File(label="Upload Energy CSV")

    run_button = gr.Button("Run AI Forecast")

    demo_button = gr.Button("Generate Demo Dataset")


    with gr.Row():

        current_card = gr.Number(label="⚡ Current Demand")

        predicted_card = gr.Number(label="📈 Predicted Demand")

        peak_card = gr.Number(label="⚠️ Peak Risk (%)")

        anomaly_card = gr.Number(label="🚨 Anomaly Alerts")


    result_table = gr.Dataframe(label="Prediction Results")


    gr.Markdown("## 📊 Energy Analytics")

    with gr.Row():

        chart1 = gr.Plot(label="Energy Consumption")

        chart2 = gr.Plot(label="Prediction vs Actual")


    gr.Markdown("## ⚡ Risk Monitoring")

    with gr.Row():

        chart3 = gr.Plot(label="Peak Demand Heatmap")

        chart4 = gr.Plot(label="Anomaly Detection")


    download_file = gr.File(label="Download Prediction CSV")


    run_button.click(
        predict_file,
        inputs=file_input,
        outputs=[
            current_card,
            predicted_card,
            peak_card,
            anomaly_card,
            result_table,
            chart1,
            chart2,
            chart3,
            chart4,
            download_file
        ]
    )


    demo_button.click(
        run_demo,
        inputs=None,
        outputs=[
            current_card,
            predicted_card,
            peak_card,
            anomaly_card,
            result_table,
            chart1,
            chart2,
            chart3,
            chart4,
            download_file
        ]
    )


#############################################
# SMART GRID TAB
#############################################

smart_grid = gr.Interface(
    fn=smart_grid_simulation,
    inputs=None,
    outputs=[
        gr.Dataframe(label="Grid Status"),
        gr.Plot(label="Demand vs Supply")
    ],
    title="Smart Grid Control Simulation"
)


#############################################
# MULTI TAB APP
#############################################

app = gr.TabbedInterface(
    [dashboard, smart_grid],
    ["Energy Forecasting Platform","Smart Grid Simulation"]
)


app.launch(share=True)

"""**Feature Importance Graph**"""

from xgboost import plot_importance
plot_importance(xgb_model)

"""**Model Comparison Chart (Linear Regression vs XGBoost)**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd
import plotly.express as px

# Linear Regression prediction
lr_pred = lr_model.predict(X_test)

# XGBoost prediction
xgb_pred = xgb_model.predict(X_test)

# Metrics
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))

lr_mae = mean_absolute_error(y_test, lr_pred)
xgb_mae = mean_absolute_error(y_test, xgb_pred)

lr_r2 = r2_score(y_test, lr_pred)
xgb_r2 = r2_score(y_test, xgb_pred)

# Create comparison table
comparison_df = pd.DataFrame({
    "Model": ["Linear Regression", "XGBoost"],
    "RMSE": [lr_rmse, xgb_rmse],
    "MAE": [lr_mae, xgb_mae],
    "R2 Score": [lr_r2, xgb_r2]
})

comparison_df

fig_model = px.bar(
    comparison_df,
    x="Model",
    y="RMSE",
    color="Model",
    title="Model Performance Comparison (RMSE)"
)

fig_model.show()

"""**24-Hour Future Forecast Graph**"""

def forecast_future(hours=24):

    future_data = X_test.iloc[-1:].copy()

    predictions = []

    for i in range(hours):

        pred = xgb_model.predict(future_data)[0]

        predictions.append(pred)

        future_data["Consumption"] = pred
        future_data["lag1"] = pred
        future_data["lag2"] = future_data["lag1"]

    future_df = pd.DataFrame({
        "Hour": range(1, hours+1),
        "Predicted Consumption": predictions
    })

    return future_df

future_df = forecast_future(24)

fig_future = px.line(
    future_df,
    x="Hour",
    y="Predicted Consumption",
    title="24-Hour Energy Demand Forecast"
)

fig_future.show()

"""**GRADIO DASHBOARD**"""

import gradio as gr
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


###############################################
# DEMO DATASET GENERATOR
###############################################

def generate_demo_dataset():

    np.random.seed(42)

    hours = 200
    base = 500
    data = []

    for i in range(hours):

        hour = i % 24

        if 18 <= hour <= 22:
            demand = base + 120 + np.random.normal(0,20)

        elif 0 <= hour <= 5:
            demand = base - 80 + np.random.normal(0,15)

        else:
            demand = base + np.random.normal(0,25)

        data.append(demand)

    df = pd.DataFrame({"Consumption":data})

    return df


###############################################
# MODEL COMPARISON CHART
###############################################

def model_comparison_chart():

    lr_pred = lr_model.predict(X_test)
    xgb_pred = xgb_model.predict(X_test)

    lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
    xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))

    lr_mae = mean_absolute_error(y_test, lr_pred)
    xgb_mae = mean_absolute_error(y_test, xgb_pred)

    lr_r2 = r2_score(y_test, lr_pred)
    xgb_r2 = r2_score(y_test, xgb_pred)

    comparison_df = pd.DataFrame({
        "Model":["Linear Regression","XGBoost"],
        "RMSE":[lr_rmse,xgb_rmse],
        "MAE":[lr_mae,xgb_mae],
        "R2":[lr_r2,xgb_r2]
    })

    fig = px.bar(
        comparison_df,
        x="Model",
        y="RMSE",
        color="Model",
        title="Model Performance Comparison"
    )

    return fig


###############################################
# 24 HOUR FORECAST
###############################################

def forecast_future(hours=24):

    future_data = X_test.iloc[-1:].copy()

    predictions=[]

    for i in range(hours):

        pred = xgb_model.predict(future_data)[0]

        predictions.append(pred)

        future_data["Consumption"]=pred
        future_data["lag1"]=pred
        future_data["lag2"]=future_data["lag1"]

    future_df = pd.DataFrame({
        "Hour":range(1,hours+1),
        "Predicted Consumption":predictions
    })

    fig = px.line(
        future_df,
        x="Hour",
        y="Predicted Consumption",
        title="24 Hour Energy Forecast"
    )

    return fig


###############################################
# AI PIPELINE
###############################################

def run_ai_pipeline(df):

    df["datetime"] = pd.date_range(
        start="2024-01-01",
        periods=len(df),
        freq="H"
    )

    df["hour"] = df["datetime"].dt.hour
    df["day_of_week"] = df["datetime"].dt.dayofweek

    df["lag1"] = df["Consumption"].shift(1)
    df["lag2"] = df["Consumption"].shift(2)

    df["rolling_mean"] = df["Consumption"].rolling(5).mean()

    df = df.dropna()

    features=[
        "Consumption",
        "lag1",
        "lag2",
        "rolling_mean",
        "hour",
        "day_of_week"
    ]

    X = df[features]

    preds = xgb_model.predict(X)

    peak_prob = classifier.predict_proba(X)[:,1]

    anomaly_scores = anomaly_model.predict(X)

    df["predicted_energy"]=preds
    df["peak_probability"]=peak_prob
    df["anomaly"]=anomaly_scores
    df["anomaly"]=df["anomaly"].map({1:"Normal",-1:"Anomaly"})


    ##################################
    # KPI METRICS
    ##################################

    current_demand = round(df["Consumption"].iloc[-1],2)
    predicted_demand = round(df["predicted_energy"].iloc[-1],2)
    peak_risk = round(df["peak_probability"].iloc[-1]*100,2)
    anomaly_count = (df["anomaly"]=="Anomaly").sum()


    ##################################
    # CHARTS
    ##################################

    energy_chart = px.line(
        df,
        x="datetime",
        y="Consumption",
        title="Energy Consumption Trend"
    )

    pred_chart = go.Figure()

    pred_chart.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["Consumption"],
        name="Actual"
    ))

    pred_chart.add_trace(go.Scatter(
        x=df["datetime"],
        y=df["predicted_energy"],
        name="Predicted"
    ))

    pred_chart.update_layout(title="Actual vs Predicted Energy")


    heatmap = px.density_heatmap(
        df,
        x="hour",
        y="day_of_week",
        z="Consumption",
        title="Peak Demand Heatmap"
    )


    anomaly_chart = px.scatter(
        df,
        x="datetime",
        y="Consumption",
        color="anomaly",
        title="Anomaly Detection"
    )


    ##################################
    # ADDITIONAL CHARTS
    ##################################

    model_chart = model_comparison_chart()

    forecast_chart = forecast_future()


    df.to_csv("prediction_output.csv",index=False)


    return (
        current_demand,
        predicted_demand,
        peak_risk,
        anomaly_count,
        df.head(20),
        energy_chart,
        pred_chart,
        heatmap,
        anomaly_chart,
        model_chart,
        forecast_chart,
        "prediction_output.csv"
    )


###############################################
# FILE INPUT
###############################################

def predict_file(file):

    if file is None:

        df = generate_demo_dataset()

    else:

        df = pd.read_csv(file)

        if "Consumption" not in df.columns:
            if "energy" in df.columns:
                df.rename(columns={"energy":"Consumption"},inplace=True)

    return run_ai_pipeline(df)


###############################################
# DEMO DATA BUTTON
###############################################

def run_demo():

    df = generate_demo_dataset()

    return run_ai_pipeline(df)


###############################################
# SMART GRID SIMULATION
###############################################

def smart_grid_simulation():

    demand=[]
    supply=[]

    base=500

    for i in range(50):

        d = base + np.random.normal(0,40)

        demand.append(d)

        if d>560:
            supply.append(580)

        elif d<450:
            supply.append(460)

        else:
            supply.append(520)

    df = pd.DataFrame({
        "time":range(50),
        "demand":demand,
        "supply":supply
    })

    fig = go.Figure()

    fig.add_trace(go.Scatter(x=df["time"],y=df["demand"],name="Demand"))
    fig.add_trace(go.Scatter(x=df["time"],y=df["supply"],name="Supply"))

    fig.update_layout(title="Smart Grid Control Simulation")

    return df,fig


###############################################
# DASHBOARD UI
###############################################

with gr.Blocks(theme=gr.themes.Soft()) as dashboard:

    gr.Markdown("# ⚡ AI Energy Intelligence Platform")

    file_input = gr.File(label="Upload Energy Dataset")

    run_button = gr.Button("Run AI Forecast")
    demo_button = gr.Button("Generate Demo Dataset")


    with gr.Row():

        current_card = gr.Number(label="⚡ Current Demand")
        predicted_card = gr.Number(label="📈 Predicted Demand")
        peak_card = gr.Number(label="⚠ Peak Risk (%)")
        anomaly_card = gr.Number(label="🚨 Anomaly Alerts")


    result_table = gr.Dataframe(label="Prediction Results")


    gr.Markdown("## Energy Analytics")

    with gr.Row():
        chart1 = gr.Plot()
        chart2 = gr.Plot()

    with gr.Row():
        chart3 = gr.Plot()
        chart4 = gr.Plot()


    gr.Markdown("## Model Insights")

    with gr.Row():
        chart5 = gr.Plot()
        chart6 = gr.Plot()


    download_file = gr.File(label="Download Results")


    run_button.click(
        predict_file,
        inputs=file_input,
        outputs=[
            current_card,
            predicted_card,
            peak_card,
            anomaly_card,
            result_table,
            chart1,
            chart2,
            chart3,
            chart4,
            chart5,
            chart6,
            download_file
        ]
    )


    demo_button.click(
        run_demo,
        inputs=None,
        outputs=[
            current_card,
            predicted_card,
            peak_card,
            anomaly_card,
            result_table,
            chart1,
            chart2,
            chart3,
            chart4,
            chart5,
            chart6,
            download_file
        ]
    )


###############################################
# SMART GRID TAB
###############################################

smart_grid = gr.Interface(
    fn=smart_grid_simulation,
    inputs=None,
    outputs=[
        gr.Dataframe(),
        gr.Plot()
    ],
    title="Smart Grid Simulation"
)


###############################################
# MULTI TAB APP
###############################################

app = gr.TabbedInterface(
    [dashboard, smart_grid],
    ["Energy Forecast Dashboard","Smart Grid Control"]
)

app.launch(share=True)

import gradio as gr
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import os

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ✅ STEP 1: MOUNT GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')

# ✅ STEP 2: CREATE FOLDER IN DRIVE
folder_path = "/content/drive/MyDrive/Energy_Project"
os.makedirs(folder_path, exist_ok=True)


###############################################
# DEMO DATASET GENERATOR
###############################################
def generate_demo_dataset():
    np.random.seed(42)
    hours = 200
    base = 500
    data = []

    for i in range(hours):
        hour = i % 24

        if 18 <= hour <= 22:
            demand = base + 120 + np.random.normal(0,20)
        elif 0 <= hour <= 5:
            demand = base - 80 + np.random.normal(0,15)
        else:
            demand = base + np.random.normal(0,25)

        data.append(demand)

    df = pd.DataFrame({"Consumption":data})
    return df


###############################################
# MODEL COMPARISON CHART
###############################################
def model_comparison_chart():
    lr_pred = lr_model.predict(X_test)
    xgb_pred = xgb_model.predict(X_test)

    lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
    xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))

    lr_mae = mean_absolute_error(y_test, lr_pred)
    xgb_mae = mean_absolute_error(y_test, xgb_pred)

    lr_r2 = r2_score(y_test, lr_pred)
    xgb_r2 = r2_score(y_test, xgb_pred)

    comparison_df = pd.DataFrame({
        "Model":["Linear Regression","XGBoost"],
        "RMSE":[lr_rmse,xgb_rmse],
        "MAE":[lr_mae,xgb_mae],
        "R2":[lr_r2,xgb_r2]
    })

    fig = px.bar(comparison_df, x="Model", y="RMSE", color="Model",
                 title="Model Performance Comparison")

    return fig


###############################################
# 24 HOUR FORECAST
###############################################
def forecast_future(hours=24):
    future_data = X_test.iloc[-1:].copy()
    predictions=[]

    for i in range(hours):
        pred = xgb_model.predict(future_data)[0]
        predictions.append(pred)

        future_data["Consumption"]=pred
        future_data["lag1"]=pred
        future_data["lag2"]=future_data["lag1"]

    future_df = pd.DataFrame({
        "Hour":range(1,hours+1),
        "Predicted Consumption":predictions
    })

    fig = px.line(future_df, x="Hour", y="Predicted Consumption",
                  title="24 Hour Energy Forecast")

    return fig


###############################################
# AI PIPELINE
###############################################
def run_ai_pipeline(df):

    df["datetime"] = pd.date_range(start="2024-01-01", periods=len(df), freq="H")
    df["hour"] = df["datetime"].dt.hour
    df["day_of_week"] = df["datetime"].dt.dayofweek

    df["lag1"] = df["Consumption"].shift(1)
    df["lag2"] = df["Consumption"].shift(2)
    df["rolling_mean"] = df["Consumption"].rolling(5).mean()

    df = df.dropna()

    features = ["Consumption","lag1","lag2","rolling_mean","hour","day_of_week"]
    X = df[features]

    preds = xgb_model.predict(X)
    peak_prob = classifier.predict_proba(X)[:,1]
    anomaly_scores = anomaly_model.predict(X)

    df["predicted_energy"] = preds
    df["peak_probability"] = peak_prob
    df["anomaly"] = anomaly_scores
    df["anomaly"] = df["anomaly"].map({1:"Normal",-1:"Anomaly"})

    ##################################
    # KPI METRICS
    ##################################
    current_demand = round(df["Consumption"].iloc[-1],2)
    predicted_demand = round(df["predicted_energy"].iloc[-1],2)
    peak_risk = round(df["peak_probability"].iloc[-1]*100,2)
    anomaly_count = (df["anomaly"]=="Anomaly").sum()

    ##################################
    # CHARTS
    ##################################
    energy_chart = px.line(df, x="datetime", y="Consumption",
                           title="Energy Consumption Trend")

    pred_chart = go.Figure()
    pred_chart.add_trace(go.Scatter(x=df["datetime"], y=df["Consumption"], name="Actual"))
    pred_chart.add_trace(go.Scatter(x=df["datetime"], y=df["predicted_energy"], name="Predicted"))
    pred_chart.update_layout(title="Actual vs Predicted Energy")

    heatmap = px.density_heatmap(df, x="hour", y="day_of_week",
                                 z="Consumption", title="Peak Demand Heatmap")

    anomaly_chart = px.scatter(df, x="datetime", y="Consumption",
                               color="anomaly", title="Anomaly Detection")

    ##################################
    # SAVE TO GOOGLE DRIVE ✅
    ##################################
    output_path = os.path.join(folder_path, "prediction_output.csv")
    df.to_csv(output_path, index=False)

    ##################################
    # ADDITIONAL CHARTS
    ##################################
    model_chart = model_comparison_chart()
    forecast_chart = forecast_future()

    return (
        current_demand,
        predicted_demand,
        peak_risk,
        anomaly_count,
        df.head(20),
        energy_chart,
        pred_chart,
        heatmap,
        anomaly_chart,
        model_chart,
        forecast_chart,
        output_path
    )


###############################################
# FILE INPUT
###############################################
def predict_file(file):
    if file is None:
        df = generate_demo_dataset()
    else:
        df = pd.read_csv(file)
        if "Consumption" not in df.columns:
            if "energy" in df.columns:
                df.rename(columns={"energy":"Consumption"}, inplace=True)

    return run_ai_pipeline(df)


###############################################
# DEMO BUTTON
###############################################
def run_demo():
    df = generate_demo_dataset()
    return run_ai_pipeline(df)


###############################################
# UI
###############################################
with gr.Blocks(theme=gr.themes.Soft()) as dashboard:

    gr.Markdown("# ⚡ AI Energy Intelligence Platform")

    file_input = gr.File(label="Upload Energy Dataset")
    run_button = gr.Button("Run AI Forecast")
    demo_button = gr.Button("Generate Demo Dataset")

    with gr.Row():
        current_card = gr.Number(label="⚡ Current Demand")
        predicted_card = gr.Number(label="📈 Predicted Demand")
        peak_card = gr.Number(label="⚠ Peak Risk (%)")
        anomaly_card = gr.Number(label="🚨 Anomaly Alerts")

    result_table = gr.Dataframe(label="Prediction Results")

    with gr.Row():
        chart1 = gr.Plot()
        chart2 = gr.Plot()

    with gr.Row():
        chart3 = gr.Plot()
        chart4 = gr.Plot()

    with gr.Row():
        chart5 = gr.Plot()
        chart6 = gr.Plot()

    download_file = gr.File(label="Download Results")

    run_button.click(
        predict_file,
        inputs=file_input,
        outputs=[
            current_card, predicted_card, peak_card, anomaly_card,
            result_table,
            chart1, chart2, chart3, chart4, chart5, chart6,
            download_file
        ]
    )

    demo_button.click(
        run_demo,
        inputs=None,
        outputs=[
            current_card, predicted_card, peak_card, anomaly_card,
            result_table,
            chart1, chart2, chart3, chart4, chart5, chart6,
            download_file
        ]
    )

app = dashboard
app.launch(share=True)

import gradio as gr
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import os
import datetime

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ✅ STEP 1: MOUNT GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')

# ✅ STEP 2: CREATE MAIN FOLDER
folder_path = "/content/drive/MyDrive/Energy_Project"
os.makedirs(folder_path, exist_ok=True)


###############################################
# DEMO DATASET GENERATOR (WITH BILLING INFO)
###############################################
def generate_demo_dataset():

    np.random.seed(42)

    hours = 200
    base = 500
    data = []

    for i in range(hours):
        hour = i % 24

        if 18 <= hour <= 22:
            demand = base + 120 + np.random.normal(0,20)
        elif 0 <= hour <= 5:
            demand = base - 80 + np.random.normal(0,15)
        else:
            demand = base + np.random.normal(0,25)

        data.append(demand)

    df = pd.DataFrame({
        "Consumption": data
    })

    # ✅ Add billing fields
    df["Name"] = "demo_user"
    df["Bill ID"] = np.random.randint(10000,99999)

    return df


###############################################
# AI PIPELINE
###############################################
def run_ai_pipeline(df):

    df["datetime"] = pd.date_range(start="2024-01-01", periods=len(df), freq="H")
    df["hour"] = df["datetime"].dt.hour
    df["day_of_week"] = df["datetime"].dt.dayofweek

    df["lag1"] = df["Consumption"].shift(1)
    df["lag2"] = df["Consumption"].shift(2)
    df["rolling_mean"] = df["Consumption"].rolling(5).mean()

    df = df.dropna()

    features = ["Consumption","lag1","lag2","rolling_mean","hour","day_of_week"]
    X = df[features]

    # ⚠ Dummy models (replace with your trained models)
    preds = X["Consumption"] + np.random.normal(0,10,len(X))
    peak_prob = np.random.rand(len(X))
    anomaly_scores = np.random.choice([1,-1], size=len(X))

    df["predicted_energy"] = preds
    df["peak_probability"] = peak_prob
    df["anomaly"] = anomaly_scores
    df["anomaly"] = df["anomaly"].map({1:"Normal",-1:"Anomaly"})

    ##################################
    # KPI
    ##################################
    current_demand = round(df["Consumption"].iloc[-1],2)
    predicted_demand = round(df["predicted_energy"].iloc[-1],2)
    peak_risk = round(df["peak_probability"].iloc[-1]*100,2)
    anomaly_count = (df["anomaly"]=="Anomaly").sum()

    ##################################
    # CHARTS
    ##################################
    energy_chart = px.line(df, x="datetime", y="Consumption")
    pred_chart = px.line(df, x="datetime", y=["Consumption","predicted_energy"])
    heatmap = px.density_heatmap(df, x="hour", y="day_of_week", z="Consumption")
    anomaly_chart = px.scatter(df, x="datetime", y="Consumption", color="anomaly")

    ##################################
    # ✅ USER-WISE FILE SAVE (FINAL)
    ##################################
    if "Name" in df.columns and "Bill ID" in df.columns:
        user_name = str(df["Name"].iloc[0]).replace(" ", "_")
        bill_id = str(df["Bill ID"].iloc[0])
    else:
        user_name = "unknown_user"
        bill_id = "0000"

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    file_name = f"{user_name}_Bill{bill_id}_{timestamp}.csv"

    # OPTIONAL: Create user folder
    user_folder = os.path.join(folder_path, user_name)
    os.makedirs(user_folder, exist_ok=True)

    output_path = os.path.join(user_folder, file_name)

    df.to_csv(output_path, index=False)

    ##################################
    return (
        current_demand,
        predicted_demand,
        peak_risk,
        anomaly_count,
        df.head(20),
        energy_chart,
        pred_chart,
        heatmap,
        anomaly_chart,
        output_path
    )


###############################################
# FILE INPUT
###############################################
def predict_file(file):

    if file is None:
        df = generate_demo_dataset()
    else:
        df = pd.read_csv(file)

        # Ensure required fields exist
        if "Consumption" not in df.columns:
            if "energy" in df.columns:
                df.rename(columns={"energy":"Consumption"}, inplace=True)

        if "Name" not in df.columns:
            df["Name"] = "user"

        if "Bill ID" not in df.columns:
            df["Bill ID"] = np.random.randint(10000,99999)

    return run_ai_pipeline(df)


###############################################
# UI
###############################################
with gr.Blocks() as app:

    gr.Markdown("# ⚡ Energy Billing & Forecast System")

    file_input = gr.File(label="Upload Dataset")

    run_btn = gr.Button("Run Prediction")

    with gr.Row():
        c1 = gr.Number(label="Current Demand")
        c2 = gr.Number(label="Predicted Demand")
        c3 = gr.Number(label="Peak Risk %")
        c4 = gr.Number(label="Anomalies")

    table = gr.Dataframe()

    with gr.Row():
        ch1 = gr.Plot()
        ch2 = gr.Plot()

    with gr.Row():
        ch3 = gr.Plot()
        ch4 = gr.Plot()

    file_out = gr.File(label="Download CSV")

    run_btn.click(
        predict_file,
        inputs=file_input,
        outputs=[c1,c2,c3,c4,table,ch1,ch2,ch3,ch4,file_out]
    )

app.launch(share=True)